### ISSUE TITLE
Decide on basic website style

### ISSUE THREAD

**Issue by justinlewis** [COWestSlopeTech/westslopetech#2]
Decide on:
1. What high level experience do we want to build toward
2. What Jekyll theme could we start with to get us there fast (https://jekyllthemes.io/). I'm not afraid to pay for one if need be.

This can all change in the future but we want to start fast to get a site live for 2018.

**Comment by aleecodes** [comment]
Not sure how this works.... but I think it'd be helpful if anyone had any websites where they like the UI/UX or the general look of the site.  Examples are always nice to have.  Maybe give a little blurb as to what you like and why you think it might be applicable for us.

**Comment by justinlewis** [comment]
I can look through the Jekyll themes later to share what I like. Maybe we can decide on a couple options and bring them to the group. Otherwise I have a ticket for hammering out basic content requirements which will help understand what type of content we will want to support. 

requirements ticket --> #4

**Comment by justinlewis** [comment]
## Some themes as a starting point

### Full theme templates
1. [Devoll](http://preview.themeforest.net/item/devoll-multipurpose-theme-powered-by-jekyll/full_screen_preview/11132266?irgwc=1&clickid=W8kwE3WjhXGs0JWSF1ULjx4wUkmVrB1tpyOeWA0&iradid=275988&irpid=27795&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=&utm_campaign=af_impact_radius&utm_medium=affiliate&utm_source=impact_radius)

2. [SquareBox]( http://preview.themeforest.net/item/squarebox-responsive-multipurpose-jekyll-theme/full_screen_preview/7688551?_ga=2.207689755.885463965.1514309316-374043873.1511299643)

3. [Agency](https://blackrockdigital.github.io/startbootstrap-agency/)
4. [Spectral](http://arkadianriver.github.io/spectral/index.html)
  
### Basic starting point themes
1. [Alembic](https://github.com/daviddarnes/alembic)
