### ISSUE TITLE
The whole events panel/div is link

### ISSUE THREAD

**Issue by dustinb** [COWestSlopeTech/westslopetech#44]
Mouse over any area of the events panel and href is the event.url.  Links in the description markdown are not clickable.

**Comment by jesse-cowan** [comment]
Remove the height property from the css selector of the above element.

.modBlogPost .type-title-wrapper {
   height: 100%;
   position: absolute;
   right: 0;
   left: 0;
}

Should be:

.modBlogPost .type-title-wrapper {
   position: absolute;
   right: 0;
   left: 0;
}

This will allow the image to be it's own link while not overlaying over the links in the content below.
