### ISSUE TITLE
Write initial mission statement

### ISSUE THREAD

**Issue by justinlewis** [COWestSlopeTech/westslopetech#5]

**Comment by Semi-ColonD** [comment]
Here are a list of current mission statements, work in progress....The last few are the best. 

The Roaring Fork Technologists mission is to proliferate technology education within the community through public outreach and mentorship through the development of citizen technical business acumen promoting economic stimulus opportunities within the Roaring Fork Valley securing the current lifestyle we enjoy for years to come.  

The Roaring Fork Technologists mission is to proliferate technology education within the community through public outreach by providing mentorship, support, and the development of citizen technical business acumen promoting economic stimulus opportunities within the Roaring Fork Valley securing the current lifestyle we enjoy for years to come.  

The Roaring Fork Technologists are committed to technology proliferation education within the community through public outreach by providing mentorship, support, and the development of its citizen’s technical business acumen promoting economic stimulus opportunities within the Roaring Fork Valley securing the current lifestyle we enjoy for years to come.  

The Roaring Fork Technologists will generate technology proliferation education within the community through public outreach by providing mentorship, support, and the development of its citizen’s technical business acumen promoting economic stimulus opportunities within the Roaring Fork Valley securing the current lifestyle we enjoy for years to come.  

The Roaring Fork Technologists are committed to technical business education for the purpose of generating economic stimulus and securing a lifestyle we enjoy for years to come.  

The Roaring Fork Technologists are committed to technology business education within the community for the purpose of generating economic stimulus securing a lifestyle we celebrate for years to come.  

The Roaring Fork Technologists are committed to technical business education within the community for the purpose of social collaboration generating economic stimulus in a setting where lifestyle is celebrated.

The Roaring Fork Technologists are committed to technology proliferation within the community for the purpose of technical business education, economic stimulus, and securing a lifestyle we celebrate for years to come.  

The Roaring Fork Technologists are committed to empowering technological solutions within the community for the purpose of technical business education, economic stimulus, and securing a lifestyle we celebrate for years to come.  

The Roaring Fork Technologists are committed to providing technology education and business technology integration advisement within the community for the purpose of economic stimulus and securing a lifestyle we celebrate for years to come.  

The Roaring Fork Technologists are committed to community technology business integration education within the community for the purpose of generating economic stimulus securing a lifestyle we celebrate for years to come.

**Comment by justinlewis** [comment]
I like the 3rd from the bottom with a slight variation inspired by @dustinb 's comment about "fostering":

The Roaring Fork Technologists are committed to fostering technological solutions within the community for the purpose of technical business education, economic stimulus, and securing a lifestyle we celebrate for years to come.
