### ISSUE TITLE
Collect images for site content

### ISSUE THREAD

**Issue by wardbt** [COWestSlopeTech/westslopetech#8]

**Comment by wardbt** [comment]
![2017-10-23 18 01 31](https://user-images.githubusercontent.com/6537157/34802039-cbe7f3dc-f628-11e7-8839-328639bd8a10.jpg)
![2017-10-23 17 57 49](https://user-images.githubusercontent.com/6537157/34802041-cc05f9e0-f628-11e7-9ccb-47911e636d1d.jpg)
![2017-10-23 17 56 40](https://user-images.githubusercontent.com/6537157/34802042-cc2003bc-f628-11e7-85c6-aeadec3a6058.jpg)
![2017-10-23 17 55 59](https://user-images.githubusercontent.com/6537157/34802043-cc3ef952-f628-11e7-8375-0e2627935448.jpg)
![2017-10-23 17 55 54](https://user-images.githubusercontent.com/6537157/34802045-cc56c6ae-f628-11e7-9713-46d74c3d3901.jpg)
![2017-10-23 17 53 57](https://user-images.githubusercontent.com/6537157/34802046-cc7360a2-f628-11e7-905f-b4c6047c9146.jpg)
![2017-10-23 17 50 29-2](https://user-images.githubusercontent.com/6537157/34802047-cc918e92-f628-11e7-8f95-83d411418797.jpg)
![2017-10-23 17 50 29-1](https://user-images.githubusercontent.com/6537157/34802048-ccb0787a-f628-11e7-99ca-c94b2c65d4af.jpg)
![2017-10-23 17 49 43](https://user-images.githubusercontent.com/6537157/34802049-cccd0620-f628-11e7-94e4-62d04a0358f4.jpg)
![2017-10-23 17 49 39](https://user-images.githubusercontent.com/6537157/34802050-cce8fdd0-f628-11e7-93ad-5a355312ac66.jpg)
![2017-10-23 17 29 06](https://user-images.githubusercontent.com/6537157/34802051-cd0579ce-f628-11e7-9904-afe2f49bac5d.jpg)
![2017-10-23 17 28 39](https://user-images.githubusercontent.com/6537157/34802052-cd1f9606-f628-11e7-89ab-ec35ffa0b540.jpg)
![2017-10-23 17 28 31](https://user-images.githubusercontent.com/6537157/34802054-cd4cb3a2-f628-11e7-821c-47fb3d236ef0.jpg)

**Comment by Semi-ColonD** [comment]
![sopriscow_011017](https://user-images.githubusercontent.com/13954265/34802166-545e5fa8-f629-11e7-8bfb-c2a16069d929.jpg)

**Comment by rodeodiva** [comment]
![cow with mac](https://user-images.githubusercontent.com/35315369/34803424-7891df74-f630-11e7-852d-24623c18024b.jpg)
2320 x 1060

**Comment by rodeodiva** [comment]
![img_1247 copy](https://user-images.githubusercontent.com/35315369/34803470-bcfd1336-f630-11e7-8096-d3d12003cf23.jpg)
